In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
# creating an array

array = np.array([1, 3, 2, 4, 5, 9, 8, 7, 6])

print(array) # values of the array
print(array.dtype) # the data type of the array

[1 3 2 4 5 9 8 7 6]
int64


In [15]:
# creating an array from 1 to 20
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
# accessing the first value of the array
array[0]

0

In [17]:
# accessing the last value of the array
array[-1] # negative index goes from end

19

In [18]:
# accessing the 2nd to 5th values of array
array[1:4]

array([1, 2, 3])

In [20]:
# let's create a multiple dimension array!
matrix = np.random.rand(2, 4)
print(matrix)

[[0.90695374 0.12445508 0.5195249  0.58601885]
 [0.62767432 0.98775028 0.03509294 0.98432241]]


In [21]:
# access the second row
print("second row: ", matrix[0])

# access the first column
print("first column: ", matrix[:, 0])

# access the 3rd value on the first row
print("third value on first row: ", matrix[0, 2])

second row:  [0.90695374 0.12445508 0.5195249  0.58601885]
first column:  [0.90695374 0.62767432]
third value on first row:  0.519524899977394


In [23]:
matrix.reshape(8, 1)

array([[0.90695374],
       [0.12445508],
       [0.5195249 ],
       [0.58601885],
       [0.62767432],
       [0.98775028],
       [0.03509294],
       [0.98432241]])

In [24]:
# slicing - access the second and third values on the second row
matrix[1, 1:3]

array([0.98775028, 0.03509294])

In [25]:
# basic operations
a = np.arange(4)
b = np.arange(1, 5)
print(a)
print(b)

[0 1 2 3]
[1 2 3 4]


In [27]:
print("sum: ", a+b)
print("difference: ", a-b)
print("product: ", a*b)
print("quotient: ", a/b)

sum:  [1 3 5 7]
difference:  [-1 -1 -1 -1]
product:  [ 0  2  6 12]
quotient:  [0.         0.5        0.66666667 0.75      ]


In [28]:
# dot product
np.dot(a, b)

20

In [29]:
# matrix multiplication
matrix_a = np.random.rand(3, 5) # opposite dimensions match
matrix_b = np.random.rand(5, 4)

np.matmul(matrix_a, matrix_b)

array([[1.13238734, 0.46944772, 0.75375987, 0.70326024],
       [1.43411785, 1.20917051, 1.47865522, 0.88783325],
       [0.95270334, 0.76539532, 1.24431189, 0.53104425]])

## Pandas

In [30]:
# lets create a pandas series!
values = [1, 2, 3, 4, 5]
labels = ["a", "b", "x", "y", "z"]

series = pd.Series(values, index=labels)
series

a    1
b    2
x    3
y    4
z    5
dtype: int64

In [33]:
# creating a dataframe with multiple rows -> table of e^x

df = pd.DataFrame()

df["x"] = [1, 2, 3, 4, 5]
df["y"] = [np.exp(1), np.exp(2), np.exp(3), np.exp(4), np.exp(5)]

df

x           y
0  1    2.718282
1  2    7.389056
2  3   20.085537
3  4   54.598150
4  5  148.413159

In [34]:
# lets add a column to the dataframe

df["random column"] = ["ABC", "DEF", "GHI", "JKL", "MNO"]
df

x           y random column
0  1    2.718282           ABC
1  2    7.389056           DEF
2  3   20.085537           GHI
3  4   54.598150           JKL
4  5  148.413159           MNO

In [35]:
# accessing a column
df["x"]

0    1
1    2
2    3
3    4
4    5
Name: x, dtype: int64

In [36]:
# accessing the third row
df.loc[2]

x                        3
y                20.085537
random column          GHI
Name: 2, dtype: object

In [37]:
# filter rows based on if X is even!
df[df["x"] % 2 == 0] # % is the remainder/modulus operator

x          y random column
1  2   7.389056           DEF
3  4  54.598150           JKL

In [40]:
# create a new column --> y divided by x
df["2y"] = df["y"] * 2
df

x           y random column          e          2y
0  1    2.718282           ABC   2.718282    5.436564
1  2    7.389056           DEF   3.694528   14.778112
2  3   20.085537           GHI   6.695179   40.171074
3  4   54.598150           JKL  13.649538  109.196300
4  5  148.413159           MNO  29.682632  296.826318

In [41]:
# create a conditional column
df["iseven"] = df["x"] % 2 == 0
df

x           y random column          e          2y  iseven
0  1    2.718282           ABC   2.718282    5.436564   False
1  2    7.389056           DEF   3.694528   14.778112    True
2  3   20.085537           GHI   6.695179   40.171074   False
3  4   54.598150           JKL  13.649538  109.196300    True
4  5  148.413159           MNO  29.682632  296.826318   False